package com.mybatis.plug.dao.entity;

import com.mybatis.plug.annotation.AutoFilled;
import com.mybatis.plug.enums.FilledType;

import java.io.Serializable;
import java.util.Date;

public class ProCompleteCancel implements Serializable {
    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `id`

     *
     * @boost.generated
     */
    private Long id;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `project_id`

     *
     * @boost.generated
     */
    private Long projectId;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `type`
    销号类型：经理1；总监0
     *
     * @boost.generated
     */
    private String type;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `supervision_status`
    质量安全监督情况:0未办理，1已办理
     *
     * @boost.generated
     */
    private String supervisionStatus;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `gmt_create`
    创建时间
     *
     * @boost.generated
     */
    @AutoFilled(fill={FilledType.INSERT})
    private Date gmtCreate;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `creator`
    创建人
     *
     * @boost.generated
     */
    @AutoFilled(fill={FilledType.INSERT})
    private Long creator;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `gmt_modified`
    更新时间
     *
     * @boost.generated
     */
    @AutoFilled(fill={FilledType.INSERT,FilledType.UPDATE})
    private Date gmtModified;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `operator`
    更新人
     *
     * @boost.generated
     */
    @AutoFilled(fill={FilledType.INSERT,FilledType.UPDATE})
    private Long operator;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `status`
    流程状态
     *
     * @boost.generated
     */
    private String status;

    /**
     *
     * This field was generated by Boost Generator.
     *  * This field corresponds to the database column `deleted`
    删除标记: 1未删除; 0已删除
     *
     * @boost.generated
     */
    @AutoFilled(fill={FilledType.INSERT})
    private Boolean deleted;

    /**
     * This field was generated by Boost Generator.
     * This field corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.id
     *
     * @return the value of yj_pro_complete_cancel.id
     *
     * @boost.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.id
     *
     * @param id the value for yj_pro_complete_cancel.id
     *
     * @boost.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.project_id
     *
     * @return the value of yj_pro_complete_cancel.project_id
     *
     * @boost.generated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withProjectId(Long projectId) {
        this.setProjectId(projectId);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.project_id
     *
     * @param projectId the value for yj_pro_complete_cancel.project_id
     *
     * @boost.generated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.type
     *
     * @return the value of yj_pro_complete_cancel.type
     *
     * @boost.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.type
     *
     * @param type the value for yj_pro_complete_cancel.type
     *
     * @boost.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.supervision_status
     *
     * @return the value of yj_pro_complete_cancel.supervision_status
     *
     * @boost.generated
     */
    public String getSupervisionStatus() {
        return supervisionStatus;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withSupervisionStatus(String supervisionStatus) {
        this.setSupervisionStatus(supervisionStatus);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.supervision_status
     *
     * @param supervisionStatus the value for yj_pro_complete_cancel.supervision_status
     *
     * @boost.generated
     */
    public void setSupervisionStatus(String supervisionStatus) {
        this.supervisionStatus = supervisionStatus == null ? null : supervisionStatus.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.gmt_create
     *
     * @return the value of yj_pro_complete_cancel.gmt_create
     *
     * @boost.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withGmtCreate(Date gmtCreate) {
        this.setGmtCreate(gmtCreate);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.gmt_create
     *
     * @param gmtCreate the value for yj_pro_complete_cancel.gmt_create
     *
     * @boost.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.creator
     *
     * @return the value of yj_pro_complete_cancel.creator
     *
     * @boost.generated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withCreator(Long creator) {
        this.setCreator(creator);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.creator
     *
     * @param creator the value for yj_pro_complete_cancel.creator
     *
     * @boost.generated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.gmt_modified
     *
     * @return the value of yj_pro_complete_cancel.gmt_modified
     *
     * @boost.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withGmtModified(Date gmtModified) {
        this.setGmtModified(gmtModified);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.gmt_modified
     *
     * @param gmtModified the value for yj_pro_complete_cancel.gmt_modified
     *
     * @boost.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.operator
     *
     * @return the value of yj_pro_complete_cancel.operator
     *
     * @boost.generated
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withOperator(Long operator) {
        this.setOperator(operator);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.operator
     *
     * @param operator the value for yj_pro_complete_cancel.operator
     *
     * @boost.generated
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.status
     *
     * @return the value of yj_pro_complete_cancel.status
     *
     * @boost.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withStatus(String status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.status
     *
     * @param status the value for yj_pro_complete_cancel.status
     *
     * @boost.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by Boost Generator.
     * This method returns the value of the database column yj_pro_complete_cancel.deleted
     *
     * @return the value of yj_pro_complete_cancel.deleted
     *
     * @boost.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    public ProCompleteCancel withDeleted(Boolean deleted) {
        this.setDeleted(deleted);
        return this;
    }

    /**
     * This method was generated by Boost Generator.
     * This method sets the value of the database column yj_pro_complete_cancel.deleted
     *
     * @param deleted the value for yj_pro_complete_cancel.deleted
     *
     * @boost.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by Boost Generator.
     * This method corresponds to the database table yj_pro_complete_cancel
     *
     * @boost.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", type=").append(type);
        sb.append(", supervisionStatus=").append(supervisionStatus);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", creator=").append(creator);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", operator=").append(operator);
        sb.append(", status=").append(status);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }
}