server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://rm-bp10u0e93427wkp4ako.mysql.rds.aliyuncs.com:3306/yicbridge_ss_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: yicbridge
    password: yicbridge
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:sqlmapper/*.xml,classpath:sqlmapper/ext/*.xml